Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define "vruiz-goS" do |s|
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.hostname = "vruiz-goS"

    s.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "vruiz-goS"
    end

    s.vm.synced_folder "confs/", "/vagrant/confs"
    s.vm.synced_folder "scripts/", "/vagrant/scripts"
    s.vm.provision "shell", path: "scripts/setup_server.sh"
  end
end
