Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  # Configuración del Nodo Servidor (Master)
  config.vm.define "vruiz-goS" do |s|
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.hostname = "vruiz-goS"
    s.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "vruiz-goS"
    end
    s.vm.synced_folder "scripts/", "/vagrant/scripts"
    s.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # Configuración del Nodo Worker (Agent)
  config.vm.define "vruiz-goSW" do |sw|
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.hostname = "vruiz-goSW"
    sw.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
      v.name = "vruiz-goSW"
    end
    sw.vm.synced_folder "scripts/", "/vagrant/scripts"
    sw.vm.provision "shell", path: "scripts/setup_agent.sh"
  end
end
